//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCPROJECT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company_REG
    {
        public int Company_ID { get; set; }
        public string Company_Name { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public long Contact { get; set; }
        public string Status { get; set; }
    }
}
