//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCPROJECT
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobApply
    {
        public int JApply_ID { get; set; }
        public int Job_ID { get; set; }
        public int Company_ID { get; set; }
        public int User_ID { get; set; }
        public System.DateTime ApplyDate { get; set; }
        public string Resume { get; set; }
        public string Apply_Status { get; set; }
    }
}
