//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCPROJECT
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobSearch
    {
        public int JSearch_ID { get; set; }
        public int Job_ID { get; set; }
        public int Company_ID { get; set; }
        public string Required_Skills { get; set; }
        public string Qualification { get; set; }
        public string Job_Status { get; set; }
        public System.DateTime Last_ApplyDate { get; set; }
    }
}
