//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCPROJECT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Login_Tab
    {
        public int Log_ID { get; set; }
        public int Reg_ID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Login_Type { get; set; }
        public string Login_Status { get; set; }
    }
}
